Repository CMU-17-356/dronuts2022-group4, pull requests merged in 2022-03, with the labels that each got.

#57 Updated navbar to remove loading instructions
  dronuts/front-end/src/components/NavbarScroller.tsx
Labels: frontend

#58 POST request working for Add Donut
  dronuts/front-end/src/components/AddDonutForm.tsx
  dronuts/front-end/src/components/DonutAvailabilityItem.tsx
  dronuts/front-end/src/components/DonutStore.tsx
  dronuts/front-end/src/components/DonutStoreItem.tsx
  dronuts/front-end/src/types/Donut.ts
Labels: enhancement, frontend

#59 Align entries in PurchasesList
  dronuts/front-end/src/components/PurchasesList.tsx
Labels: frontend

#61 Small backend fixes
  dronuts/back-end/src/db/models.ts
  dronuts/back-end/src/index.ts
Labels: bug, backend

#55 Interactive checkout experience
  dronuts/back-end/src/db/models.ts
  dronuts/back-end/tests/schema.test.ts
  dronuts/front-end/src/components/DonutStore.tsx
  dronuts/front-end/src/components/DonutStoreCheckout.tsx
  dronuts/front-end/src/components/DonutStoreItem.tsx
  dronuts/front-end/src/components/LoginPage.tsx
  dronuts/front-end/src/types/Donut.ts
  dronuts/front-end/src/types/DonutCart.ts
  dronuts/front-end/src/types/Order.ts
  dronuts/front-end/src/types/User.ts
Labels: frontend, backend

#66 Order flow
  dronuts/back-end/src/db/models.ts
  dronuts/front-end/package-lock.json
  dronuts/front-end/package.json
  dronuts/front-end/src/components/DonutStoreCheckout.tsx
  dronuts/front-end/src/components/EmployeeNotificationSystem.tsx
  dronuts/front-end/src/components/EmployeeNotificationSystemOrder.tsx
  dronuts/front-end/src/components/LoginPage.tsx
  dronuts/front-end/src/components/OrderStatus.tsx
  dronuts/front-end/src/components/PurchasesList.tsx
  dronuts/front-end/src/index.tsx
  package-lock.json
  package.json
Labels: enhancement, frontend, backend

#69 Fixing the Signup Page
  dronuts/back-end/src/db/models.ts
  dronuts/back-end/src/index.ts
  dronuts/front-end/public/favicon.ico
  dronuts/front-end/src/components/DonutStore.tsx
  dronuts/front-end/src/components/LoginPage.tsx
  dronuts/front-end/src/components/SignUpForm.tsx
Labels: bug, enhancement, frontend

#68 Received order button functionality
  dronuts/front-end/src/components/EmployeeNotificationSystemOrder.tsx
  dronuts/front-end/src/components/OrderStatus.tsx
Labels: enhancement, frontend

#72 Navbar restrictions
  dronuts/back-end/src/index.ts
  dronuts/front-end/src/components/DonutStore.tsx
  dronuts/front-end/src/components/HomePage.tsx
  dronuts/front-end/src/components/NavbarScroller.tsx
  dronuts/front-end/src/components/SignUpForm.tsx
Labels: enhancement, frontend

#73 User type dropdown bug fix
  dronuts/front-end/src/components/SignUpForm.tsx
Labels: enhancement, frontend

#74 Refresh ENS after employee completes order
  dronuts/front-end/src/components/EmployeeNotificationSystem.tsx
  dronuts/front-end/src/components/EmployeeNotificationSystemOrder.tsx
Labels: bug, enhancement, tentative_complete, frontend

#75 Display active order
  dronuts/front-end/src/components/OrderStatus.tsx
Labels: enhancement, frontend

#76 fix: Made list items show up in different rows for purchase lit
  dronuts/front-end/src/components/PurchasesList.tsx
Labels: bug, frontend

#77 feat: Created E2E testing for home, sign up, and log in page
  cypress.json
  cypress/fixtures/example.json
  dronuts/front-end/src/components/LoginPage.tsx
  dronuts/front-end/src/components/SignUpForm.tsx
  package-lock.json
  package.json
Labels: enhancement, tentative_complete

#78 scm: Added appropriate file to gitignore so cypress tests appear
  .gitignore
  cypress/integration/e2e.test.js
Labels: bug, scm

#79 faet: Added E2E for checkout page
  cypress/integration/e2e.test.js
Labels: enhancement

#80 feat: Added cypress E2E tests for owner
  cypress/integration/e2e.test.js
  dronuts/front-end/src/components/AddDonutForm.tsx
  dronuts/front-end/src/components/DonutStoreCheckout.tsx
Labels: frontend, scm

#82 scm: Merged the E2E tests
  cypress/integration/e2e-aashai.test.js
  cypress/integration/e2e.test.js
Labels: scm

#71 Add dynamic content to drone status view
  dronuts/front-end/src/components/DroneStatus.tsx
  dronuts/front-end/src/types/Drone.ts
Labels: frontend

#83 fix: Modified drone API endpoints so the data is retrieved
  cypress/integration/e2e.test.js
  dronuts/front-end/src/components/DroneStatus.tsx
  dronuts/front-end/src/types/Drone.ts
Labels: bug, enhancement, frontend
