Repository CMU-17-356/dronuts2022-group4, pull requests merged in 2022-02, with the labels that each got.

#28 Transition from loopback to express for codebase set up
  .vscode/launch.json
  dronuts/back-end/fakeDonuts.json
  dronuts/back-end/package-lock.json
  dronuts/back-end/package.json
  dronuts/back-end/src/index.js
  dronuts/back-end/src/index.ts
  dronuts/back-end/tsconfig.json
  dronuts/front-end/.gitignore
  dronuts/front-end/README.md
  dronuts/front-end/package-lock.json
  dronuts/front-end/package.json
  dronuts/front-end/public/index.html
  dronuts/front-end/public/manifest.json
  dronuts/front-end/src/App.css
  dronuts/front-end/src/index.css
  dronuts/front-end/src/react-app-env.d.ts
  dronuts/front-end/src/reportWebVitals.ts
  dronuts/front-end/src/setupTests.ts
  dronuts/front-end/tsconfig.json
  dronuts/package-lock.json
  dronuts/package.json
  dronuts/public/index.html
  dronuts/src/__tests__/README.md
  dronuts/src/__tests__/acceptance/home-page.acceptance.ts
  dronuts/src/__tests__/acceptance/ping.controller.acceptance.ts
  dronuts/src/__tests__/acceptance/test-helper.ts
  dronuts/src/application.ts
  dronuts/src/controllers/README.md
  dronuts/src/controllers/hello.controller.ts
  dronuts/src/controllers/index.ts
  dronuts/src/controllers/ping.controller.ts
  dronuts/src/datasources/README.md
  dronuts/src/index.ts
  dronuts/src/migrate.ts
  dronuts/src/models/README.md
  dronuts/src/openapi-spec.ts
  dronuts/src/repositories/README.md
  dronuts/src/sequence.ts
  dronuts/tsconfig.json
  tsconfig.tsbuildinfo
Labels: scm

#30 Fix gitignore so that components folder with content appears
  .gitignore
  dronuts/front-end/public/robots.txt
  dronuts/front-end/src/App.test.tsx
  dronuts/front-end/src/App.tsx
  dronuts/front-end/src/components/DonutAvailability.tsx
  dronuts/front-end/src/components/DonutAvailabilityItem.tsx
  dronuts/front-end/src/components/OrderStatus.tsx
  dronuts/front-end/src/google_maps_api_credentials.json
  dronuts/front-end/src/index.tsx
Labels: scm

#37 CI Setup
  .github/workflows/frontend-build-test.yml
  .github/workflows/github-actions-demo.yml
  .gitignore
  dronuts/back-end/src/index.js
  dronuts/back-end/src/index.ts
  dronuts/front-end/src/App.tsx
  dronuts/front-end/src/components/DonutStore.tsx
  dronuts/front-end/src/components/DonutStoreCheckout.tsx
  dronuts/front-end/src/components/DonutStoreItem.tsx
Labels: scm

#34 Donut Store pages
  .gitignore
  dronuts/back-end/src/index.js
  dronuts/back-end/src/index.ts
  dronuts/front-end/src/App.tsx
  dronuts/front-end/src/components/DonutStore.tsx
  dronuts/front-end/src/components/DonutStoreCheckout.tsx
  dronuts/front-end/src/components/DonutStoreItem.tsx
Labels: frontend

#35 Add drone status page
  dronuts/front-end/src/components/DroneStatus.tsx
  dronuts/front-end/src/images/drone.png
Labels: frontend

#36 Add purchase list page
  dronuts/front-end/src/components/PurchasesList.tsx
Labels: frontend

#33 Set up ODM models with tests
  .gitignore
  dronuts/back-end/jest.config.js
  dronuts/back-end/package-lock.json
  dronuts/back-end/package.json
  dronuts/back-end/src/db/models.ts
  dronuts/back-end/src/index.js
  dronuts/back-end/tests/schema.test.ts
  dronuts/back-end/tests/utility.ts
  package-lock.json
  package.json
Labels: enhancement, scm, backend

#39 Proper routing implemented
  dronuts/front-end/package-lock.json
  dronuts/front-end/package.json
  dronuts/front-end/src/App.tsx
  dronuts/front-end/src/components/DonutAvailability.tsx
  dronuts/front-end/src/components/DonutAvailabilityItem.tsx
  dronuts/front-end/src/components/NavbarScroller.tsx
  dronuts/front-end/src/components/OrderStatus.tsx
  dronuts/front-end/src/index.tsx
Labels: frontend

#40 Employee Notification System Page
  dronuts/back-end/fakeDonuts.json
  dronuts/front-end/src/App.tsx
  dronuts/front-end/src/components/DonutAvailability.tsx
  dronuts/front-end/src/components/DonutAvailabilityItem.tsx
  dronuts/front-end/src/components/EmployeeNotificationSystem.tsx
  dronuts/front-end/src/index.tsx
Labels: enhancement, frontend, scm

#42 feat: Designed and implemented home page
  dronuts/front-end/src/App.css
  dronuts/front-end/src/App.tsx
  dronuts/front-end/src/components/HomePage.tsx
  dronuts/front-end/src/images/dronut.png
  package-lock.json
  package.json
Labels: enhancement, frontend

#43 Create Dynamic Employee Notification System
  dronuts/back-end/fakeOrders.json
  dronuts/back-end/src/index.ts
  dronuts/front-end/src/App.tsx
  dronuts/front-end/src/components/EmployeeNotificationSystem.tsx
  dronuts/front-end/src/components/EmployeeNotificationSystemOrder.tsx
Labels: enhancement, frontend

#46 feat: Improved the visuals of the admin store page.
  dronuts/back-end/fakeDonuts.json
  dronuts/front-end/src/components/DonutAvailabilityItem.tsx
Labels: enhancement, frontend

#48 Cart now stored in local storage
  dronuts/front-end/src/components/DonutStore.tsx
  dronuts/front-end/src/components/DonutStoreCheckout.tsx
  dronuts/front-end/src/components/DonutStoreItem.tsx
  dronuts/front-end/src/types/Donut.ts
  dronuts/front-end/src/types/DonutCart.ts
  dronuts/front-end/src/util/useLocalStorage.ts
Labels: frontend

#51 ENS Visual Improvements
  dronuts/front-end/src/components/EmployeeNotificationSystem.tsx
Labels: enhancement, frontend

#52 Login page
  dronuts/back-end/fakeUsers.json
  dronuts/back-end/src/db/models.ts
  dronuts/back-end/src/index.ts
  dronuts/back-end/tests/schema.test.ts
  dronuts/front-end/src/components/HomePage.tsx
  dronuts/front-end/src/components/HomePageStyle.css
  dronuts/front-end/src/components/LoginPage.tsx
  dronuts/front-end/src/components/LoginPageStyle.css
  dronuts/front-end/src/index.tsx
Labels: enhancement, frontend

#53 feat: Improved UI of the store page
  dronuts/front-end/src/components/DonutAvailability.tsx
  dronuts/front-end/src/components/DonutAvailabilityItem.tsx
  dronuts/front-end/src/components/DonutStore.tsx
  dronuts/front-end/src/components/DonutStoreItem.tsx
  dronuts/front-end/src/types/Donut.ts
Labels: enhancement, frontend

#54 Backend endpoints
  dronuts/back-end/notes.md
  dronuts/back-end/src/db/models.ts
  dronuts/back-end/src/index.ts
  dronuts/back-end/tests/schema.test.ts
Labels: backend
